runmode: debug  #运行模式有三种 debug/release/test
addr: :8080     #运行端口
name: gin-demo  #实例的名字
url: http://127.0.0.1:8080  #ping的地址
max_ping_count: 10  #ping的最大次数
log:
  writers: file,stdout #输出流,既有文件也有标准输出
  logger_level: DEBUG   #日志级别五种 DEBUG/INFO/WARN/ERROR/FATAL
  logger_file: log/gin_demo.log   #日志文件位置
  log_format_text: false    #日志的输出文件格式,false-->json,true-->plaintext
  rollingPolicy: size       #rotate依据(转存),可选daily-->根据天来转存,可选size-->根据大小来转存
  log_rotate_date: 1        #配合rollingPolicy: daily 选择几天来转存
  log_rotate_size: 1        #配合rollingPolicy: size  选择几天来转存
  log_backup_count: 7       #日志文件达到转存标准后会压缩备份, 这里指定压缩文件的最大个数
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: @Bowser1704
